[platformio]
default_envs = freenove_esp32_s3_wroom

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino

monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  hieromon/AutoConnect @ ^1.4.2

  ; âœ… richtige HUB75 Library (ESP32 / S2 / S3)
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git

  Adafruit GFX Library
  https://github.com/taranais/NTPClient
  gyverlibs/UnixTime @ ^1.1

build_flags =
  -D DEBUG
  -D MONITOR_SPEED=115200
  -D BOARD_HAS_PSRAM

board_build.arduino.memory_type = qio_opi

[env:ota]
extends = env:freenove_esp32_s3_wroom
upload_protocol = espota
upload_port = 192.168.1.33  ; replace with your display's IP
upload_flags = --auth=vbz1234
